### PR TITLE
refactor: avoid concatMap over used

### PR DESCRIPTION
**Pull request by sandangel**

### CODE REVIEW

**Comment by isaacplmann** [comment]
Is this PR functionally equivalent to the existing code?

**Comment by sandangel** [comment]
yeah. I think it's the same. ^^

**Comment by isaacplmann** [comment]
Ok, just making sure I wasn't missing anything.

**Comment by sandangel** [comment]
I have not tested it yet. I think we should have an integration test in CI

**Comment by isaacplmann** [comment]
yeah, I'd take a PR for that.  I won't publish a new version on npm until I've tested it out

**Pull request merged**
